# Generated by Django 5.2.14 on 2026-05-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='HEAD', max_length=255)),
                ('revision', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('edge_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='api.analysisrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='github', max_length=32)),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=511)),
                ('default_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('clone_url', models.URLField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'full_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'full_name'), name='unique_repository_provider_full_name')],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='api.repository'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['repository', 'revision', 'status'], name='api_analysi_reposit_7ef57a_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('repository', 'revision'), name='unique_succeeded_analysis_run_per_revision'),
        ),
    ]
