# Generated by Django 5.2.14 on 2026-05-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('mode', models.CharField(choices=[('fixed', 'Fixed revision'), ('latest', 'Latest branch')], default='fixed', max_length=32)),
                ('ref', models.CharField(default='HEAD', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_links', to='api.analysisrun')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='api.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_active'], name='api_shareli_token_cc22e4_idx'), models.Index(fields=['repository', 'mode'], name='api_shareli_reposit_341620_idx')],
            },
        ),
    ]
