# Generated by Django 5.2.14 on 2026-06-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sharelink'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysisrun',
            name='unique_succeeded_analysis_run_per_revision',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analysis_profile',
            field=models.CharField(default='python-v1', max_length=128),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['repository', 'revision', 'analysis_profile', 'status'], name='api_analysi_reposit_1f5e83_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('repository', 'revision', 'analysis_profile'), name='unique_succeeded_analysis_run_per_revision_profile'),
        ),
    ]
