"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMP_DIR = BASE_DIR / 'temp'
PLAYGROUND_DIR = BASE_DIR / 'playground'

TEMP_DIR.mkdir(exist_ok=True)
PLAYGROUND_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() == 'true'


def _env_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    return int(value.strip())


def _env_list(name: str, default: list[str]) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return default
    return [item.strip() for item in value.split(',') if item.strip()]


IS_TESTING = 'test' in sys.argv


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if IS_TESTING:
        SECRET_KEY = 'django-test-secret-key'
    else:
        raise RuntimeError('SECRET_KEY environment variable is required')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if IS_TESTING else _env_bool('DEBUG', False)

ALLOWED_HOSTS = ['testserver', 'localhost', '127.0.0.1'] if IS_TESTING else _env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])
CSRF_TRUSTED_ORIGINS = [] if IS_TESTING else _env_list('CSRF_TRUSTED_ORIGINS', [])
SECURE_SSL_REDIRECT = False if IS_TESTING else _env_bool('SECURE_SSL_REDIRECT', False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = False if IS_TESTING else not DEBUG
CSRF_COOKIE_SECURE = False if IS_TESTING else not DEBUG

GITHUB_REPO_GIT_TIMEOUT_SECONDS = _env_int('GITHUB_REPO_GIT_TIMEOUT_SECONDS', 30)
GITHUB_REPO_MAX_FILES = _env_int('GITHUB_REPO_MAX_FILES', 5000)
GITHUB_REPO_MAX_PYTHON_FILES = _env_int('GITHUB_REPO_MAX_PYTHON_FILES', 1000)
GITHUB_REPO_MAX_JS_TS_FILES = _env_int('GITHUB_REPO_MAX_JS_TS_FILES', 2500)
GITHUB_REPO_MAX_SINGLE_FILE_BYTES = _env_int('GITHUB_REPO_MAX_SINGLE_FILE_BYTES', 300_000)
GITHUB_REPO_MAX_TOTAL_ANALYZED_BYTES = _env_int('GITHUB_REPO_MAX_TOTAL_ANALYZED_BYTES', 5_000_000)
GITHUB_REPO_REVISION_FETCH_DEPTH = _env_int('GITHUB_REPO_REVISION_FETCH_DEPTH', 50)
ANALYZER_PROFILE_ID = os.getenv('ANALYZER_PROFILE_ID', 'multi-lang-js-ts-v1')
_DEFAULT_REPO_ENABLED_LANGUAGES = ['python', 'javascript', 'typescript'] if ANALYZER_PROFILE_ID == 'multi-lang-js-ts-v1' else ['python']
GITHUB_REPO_ENABLED_LANGUAGES = _env_list('GITHUB_REPO_ENABLED_LANGUAGES', _DEFAULT_REPO_ENABLED_LANGUAGES)
GITHUB_API_BASE_URL = os.getenv('GITHUB_API_BASE_URL', 'https://api.github.com').rstrip('/')
GITHUB_API_TIMEOUT_SECONDS = _env_int('GITHUB_API_TIMEOUT_SECONDS', 10)
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', '')
ISSUES_USE_MOCK = _env_bool('ISSUES_USE_MOCK', False)
ISSUE_MAP_LLM_ENABLED = _env_bool('ISSUE_MAP_LLM_ENABLED', False)
ISSUE_HARNESS_ENABLED = _env_bool('ISSUE_HARNESS_ENABLED', ISSUE_MAP_LLM_ENABLED)
QA_HARNESS_ENABLED = _env_bool('QA_HARNESS_ENABLED', False)
ISSUE_HARNESS_COMMAND = os.getenv('ISSUE_HARNESS_COMMAND', '')
ISSUE_HARNESS_TIMEOUT_SECONDS = _env_int('ISSUE_HARNESS_TIMEOUT_SECONDS', 180)
SHARE_CREATE_THROTTLE_RATE = os.getenv('SHARE_CREATE_THROTTLE_RATE', '60/hour')
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', '').rstrip('/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'api',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'share_create': SHARE_CREATE_THROTTLE_RATE,
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
